function [s,r,sh,w,thresh] = wprSIG(price,N,thresh,scaling,cost,bigPoint)
%WPRSIG WPR signal generator from 'willpctr.m' function by The MathWorks, Inc.
% WPRSIG trading strategy.  Note that the trading signal is generated when the
% WPR value is above/below the upper/lower threshold.
% N serves as an optional lookback period (default 14 observations)
%
%   NOTE: It is important to consider that a WPR signal generator really has 3 states.
%           Above Threshold is Overbought
%           Below Threshold is Oversold
%           There is also a neutral region between +/- Threshold and 50%
%
%   This should be considered prior to adding or removing any Echos to this output.
%   For calculating a direct PNL, the signal should first be cleaned with remEcho_mex.
%
%   INPUTS:
%           price       an array of any [C] or [O | C] or [O | H | L | C]
%           N           observation lookback period
%           thresh      threshold of overbought / oversold (X | [X 100-X] is submitted)
%           scaling     sharpe ratio adjuster
%           cost        round turn commission cost for proper P&L calculation
%           bigPoint    Full tick dollar value of security
%   OUTPUTS:
%           s           The generated output SIGNAL
%           r           Return generated by the derived signal
%           sh          Sharpe ratio generated by the derived signal
%           w           WPR values generated by the call to 'willpctr.m'
%           thresh      Echos the input threshold value (primarily for debugging)
%

%% MEX code to be skipped
coder.extrinsic('OHLCSplitter','willpctr','remEchos_mex','calcProfitLoss','sharpe')

% WPR works with negative values in a range from 0 to -100;
if numel(thresh) == 1 % scalar value
    thresh = [(100-abs(thresh))*-1, abs(thresh)*-1];
else
    thresh = abs(thresh)*-1;
end;
if thresh(1) < thresh(2)
    thresh= thresh(2:-1:1);
end;

if thresh(1) > 0, thresh(1) = thresh(1) * -1; end;
if thresh(2) > 0, thresh(2) = thresh(2) * -1; end;

% Preallocate so we can MEX
rows = size(price,1);
fOpen = zeros(rows,1);                                      %#ok<NASGU>
fClose = zeros(rows,1);                                     %#ok<NASGU>
fHigh = zeros(rows,1);                                      %#ok<NASGU>
fLow = zeros(rows,1);                                       %#ok<NASGU>
s = zeros(rows,1);
w = zeros(rows,1);                                          %#ok<NASGU>

if size(price,2) == 4
    [fOpen, fHigh, fLow, fClose] = OHLCSplitter(price);
else
    error('wprMETS:InputArg',...
        'We need as input O | H | L | C.');
end; %if

%% williams %r
w = willpctr([fHigh fLow fClose],N);

%% generate signal
% Crossing the upper threshold (overbought)
indx = w > thresh(1);
s(indx) = -1.5;

indx = w < thresh(2);
s(indx) = 1.5;

if ~isempty(find(s,1))
    % Clean up repeating information so we can calculate a PNL
    s = remEchos_mex(s);
    
    %% PNL Caclulation
    [~,~,~,r] = calcProfitLoss([fOpen fClose],s,bigPoint,cost);
    sh = scaling*sharpe(r,0);
else
    % No signal - no return or sharpe
    r = zeros(length(fClose),1);
    sh = 0;
end; %if

%%
%   -------------------------------------------------------------------------
%        This code is distributed in the hope that it will be useful,
%
%                      	   WITHOUT ANY WARRANTY
%
%                  WITHOUT CLAIM AS TO MERCHANTABILITY
%
%                  OR FITNESS FOR A PARTICULAR PURPOSE
%
%                          expressed or implied.
%
%   Use of this code, pseudocode, algorithmic or trading logic contained
%   herein, whether sound or faulty for any purpose is the sole
%   responsibility of the USER. Any such use of these algorithms, coding
%   logic or concepts in whole or in part carry no covenant of correctness
%   or recommended usage from the AUTHOR or any of the possible
%   contributors listed or unlisted, known or unknown.
%
%   Any reference of this code or to this code including any variants from
%   this code, or any other credits due this AUTHOR from this code shall be
%   clearly and unambiguously cited and evident during any use, whether in
%   whole or in part.
%
%   The public sharing of this code does not reliquish, reduce, restrict or
%   encumber any rights the AUTHOR has in respect to claims of intellectual
%   property.
%
%   IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY
%   DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
%   DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
%   OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
%   HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
%   STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
%   ANY WAY OUT OF THE USE OF THIS SOFTWARE, CODE, OR CODE FRAGMENT(S), EVEN
%   IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
%
%   -------------------------------------------------------------------------
%
%                             ALL RIGHTS RESERVED
%
%   -------------------------------------------------------------------------
%
%   Author:	Mark Tompkins
%   Revision:	4906.24976
%   Copyright:	(c)2013
%
